import Image from 'next/image'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Main from '@/components/Main';
import About from '@/components/About';
import Technologies from '@/components/Technologies';
import Projects from '@/components/Projects';
import LearningProjects from '@/components/LearningProjects';


export default function Home() {
  return (
  <div>
    <Head>
      <title>Armandas | Front-End Developer</title>
      <meta name='description' content='Generated by next js' />
      <link rel="icon" href="/assets/navLogo.png" />
    </Head>
    <Navbar />
    <Main />
    <About />
    <Technologies />
    <Projects />
    {/* <LearningProjects /> */}
  </div>
  );
  
}
